DjangoWebProject3/urls.py
"""
Definition of urls for DjangoWebProject3.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

from django.contrib import admin
from django.urls import include, path

import app.forms
import app.views

# Uncomment the next lines to enable the admin:
# from django.conf.urls import include
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about', app.views.about, name='about'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),
    path('testapp/', include('testapp.urls')),  #自分のアプリを登録する
    path('admin/', admin.site.urls),            #管理サイトを登録する

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
]

test2/test2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

testapp/urls.py
from django.urls import path

from . import views

app_name = 'testapp'    #アプリの名前空間定義。templateからURLを正確に判断するためのもの
urlpatterns = [
    #path('', views.index, name='index'),

    #path('<int:question_id>/', views.detail, name='detail'),
    #path('<int:question_id>/results/', views.results, name='results'),
#------------------------------------------------------------------------------------------------
# 以下は汎用ビューを使った書き方
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),

    path('<int:question_id>/vote/', views.vote, name='vote'),
]

testapp/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now >= self.pub_date >= now - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

# Create your models here.

testapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from .models import Choice, Question
from django.template import loader
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.db.models import F
from django.utils import timezone


#def index(request):
#    return HttpResponse("Hello, world. You're at the polls index.")        #テスト出力
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]       #Questionオブジェクトの最新5件を表示
    #output = ', '.join([q.question_text for q in latest_question_list])    #出力リスト作成。デバッグに使えそう
    template = loader.get_template('testapp/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    #return HttpResponse(output)                                            #作成した出力リストをHttpResponseに詰めて返す。デバッグでとりあえず出力する際に使えそう
    #return HttpResponse(template.render(context, request))                 #HttpResponseにtemplateを詰めて返すやり方
    return render(request, 'testapp/index.html', context)                   #renderでtemplateを直接指定。これが一番シンプル

#def detail(request, question_id):
#    return HttpResponse("You're looking at question %s." % question_id)    #テスト出力
#def detail(request, question_id):                                          #オブジェクトをgetし存在しなければ404エラー。しかしコードが冗長である
#    try:
#        question = Question.objects.get(pk=question_id)
#    except Question.DoesNotExist:
#        raise Http404("Question does not exist")
#    return render(request, 'testapp/detail.html', {'question': question})
def detail(request, question_id):                                           #get_object_or_404のショートカットを使ってオブジェクト取得と404エラー判定を同時に行う
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'testapp/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'testapp/results.html', {'question': question})

#---------------------------------------------------------------------------------------------------------------------------------------
# 以上は簡単だが冗長な書き方。以下は汎用ビューを使った書き方
class IndexView(generic.ListView):
    template_name = 'testapp/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        #"""Return the last five published questions."""
        #return Question.objects.order_by('-pub_date')[:5]
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(     # 現在日時より未来（公開日時前）のQuestionは表示しない
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'testapp/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'testapp/results.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

def vote(request, question_id):
    # Questionオブジェクトを取得
    question = get_object_or_404(Question, pk=question_id)
    try:
        # formで渡されたchoice_idからchoiceオブジェクトを取得
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # postメソッドにchoiceが存在しなければエラー
        return render(request, 'testapp/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        # オブジェクト取得に成功していれば投票数を加算し、DB保存。
        #selected_choice.votes += 1
        # F()でDBアクセスの競合を防いでくれるらしい。see also"https://docs.djangoproject.com/ja/2.1/ref/models/expressions/#avoiding-race-conditions-using-f"
        # "https://qiita.com/okoppe8/items/66a8747cf179a538355b"
        selected_choice.votes = F('votes') + 1;
        selected_choice.save()
        
        # 結果ページへリダイレクト
        return HttpResponseRedirect(reverse('testapp:results', args=(question.id,)))

# Create your views here.

testapp/templates/testapp/detail.html
<html>
    <head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head>
    <body>
       <h1>{{ question.question_text }}</h1>
       
       <form action="{% url 'testapp:vote' question.id %}" method="post">   {#url読み出し。testappのvoteはviews.vote#}
       {% csrf_token %}                                                     {#クロスサイトリクエストフォージェリ(CSRF) を防ぐためのモノ。see also"http://d.hatena.ne.jp/blaue_fuchs/20111014/1318520988"#}
       {% for choice in question.choice_set.all %}                          {#独特な書き方。questionオブジェクトから外部キーで紐づくmodelクラスであるchoiceを自動で探してくれてるらしい。#}
           <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">  {#ループカウンタは自作しなくてもforloop.counterで取れるらしい。#}
           <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>                {#choice_textをラベルとしてラジオボタン作成#}
       {% endfor %}
       <input type="submit" value="Vote">
       </form>
       <a href="{% url 'testapp:index'%}">TOP</a>
    </body>
</html>

testapp/templates/testapp/index.html
{% load static %}                                                                    {#staticファイルの完全URL生成#}
<link rel="stylesheet" type="text/css" href="{% static 'testapp/css/style.css' %}">  {#staticCSSファイル読み込み#}
<script type="text/javascript" src="{% static 'testapp/js/sample.js' %}"></script>                            {#staticJAVASCRIPTファイル読み込み#}
<html>
<link href="https://fonts.googleapis.com/css?family=M+PLUS+1p" rel="stylesheet">
    <head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head>
    <body>
        {% if latest_question_list %}   {#事前にpythonで設定したオブジェクトはこちらで参照可能#}
        <div class="bgsize">
            <ul>
            {% for question in latest_question_list %}                                                      {#ループ処理。latest_question_listをイテレートしている。#}
                {#<li><a href="/testapp/{{ question.id }}/">{{ question.question_text }}</a></li>#}        {#{{????}}はdjango templateの独自の書き方。#}
                <li class="colchan"><a href="{% url 'testapp:detail' question.id %}">{{ question.question_text }}</a></li>  {#URLを直書きせずにurlsで定義したdetailのURLを参照する。#}
            {% endfor %}
            </ul>
        </div>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
    </body>
</html>

testapp/templates/testapp/results.html
<html>
    <head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head>
    <body>
       <h1>{{ question.question_text }}</h1>

       <ul>
       {% for choice in question.choice_set.all %}
           <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
       {% endfor %}
       </ul>

       <a href="{% url 'testapp:detail' question.id %}">Vote again?</a>
    </body>
    <p><a href="{% url 'testapp:index'%}">TOP</a></p>
</html>